# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "ko-KR"
early_access: false

reviews:
  profile: "chill"
  high_level_summary: true
  poem: false

  request_changes_workflow: true

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "dev"
      - "main"

chat:
  auto_reply: true